def COLOR_MAP = [
    'SUCCESS' : 'good',
    'FAILURE' : 'danger',
]
pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "Oraclejdk8"
    }

    environment {
        cluster = "vproprod"
        service = "vproprodsvc"
    }  

    stages {
        stage('Deploy to ECS Production') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
    post {
        always {
            echo 'slack notification'
            slackSend channel: '#cicd-project',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${BUILD_NUMBER} \n More info you can find at: ${env.BUILD_URL}"
        }
    }
}